version: '3'

services:
  gatsby:
    working_dir: /home/gatsby-app
    build:
      context: ./gatsby
      dockerfile: Dockerfile
    depends_on:
      - strapi
      - db
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    environment:
      GATSBY_WEBPACK_PUBLICPATH: /
      STRAPI_URL: strapi:1337
    command: ["./gatsby/wait-for-strapi.sh"]
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    environment:
      - APP_NAME=strapi-project
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-project:/usr/src/api/strapi-project
#      - /usr/src/api/strapi-project/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
